[project]
name = "mangaanalysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10,<4",
    "numpy>=2.3,<3",
    "onnx>=1.21.0",
    "onnxconverter-common>=1.16.0",
    "onnxruntime>=1.26.0",
    "opencv-python>=4.12,<5",
    "pillow>=11.3,<12",
    "torch>=2.11.0,<2.12",
    "torchvision>=0.26.0,<0.27",
    "wgpu>=0.31.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30,<7",
    "ipython>=9.7,<10",
]

[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

