import type { Candidate, PanelBox, PanelGuidedSelectionSource, PanelGuidedStepState, Point, RoiRect } from "../../types/simulation";

/**
 * Return the detected panels sorted by the manga reading order generated by the panel detector.
 */
export function orderPanelsByReadingOrder(panels: PanelBox[], readingOrder: number[]): PanelBox[] {
  const panelById = new Map<number, PanelBox>(panels.map((panel) => [panel.panelId, panel]));
  return readingOrder.map((panelId) => panelById.get(panelId)).filter((panel): panel is PanelBox => panel !== undefined);
}

/**
 * Find the ordered-panel index that contains the fixation, or fall back to the first panel.
 */
export function findPanelIndexForFixation(panels: PanelBox[], fixation: Point): number {
  for (let index = 0; index < panels.length; index += 1) {
    if (rectContainsPoint(panels[index].rect, fixation)) {
      return index;
    }
  }
  return 0;
}

/**
 * Return the geometric center of one panel rectangle.
 */
export function panelCenter(panel: PanelBox): Point {
  return {
    x: panel.rect.x + panel.rect.width * 0.5,
    y: panel.rect.y + panel.rect.height * 0.5,
  };
}

/**
 * Keep only the candidates that fall inside the provided panel rectangle.
 */
export function filterCandidatesToPanel(candidates: Candidate[], panel: PanelBox | null): Candidate[] {
  if (!panel) {
    return [];
  }
  return candidates.filter((candidate) => rectContainsPoint(panel.rect, { x: candidate.pageX, y: candidate.pageY }));
}

type BuildPanelGuidedStepParams = {
  currentFixation: Point;
  currentPanelIndex: number;
  orderedPanels: PanelBox[];
  localRoi: RoiRect;
  localCandidates: Candidate[];
  fallbackCandidates: Candidate[];
  stepIndex: number;
};

type BuildPanelGuidedStepResult = {
  nextFixation: Point | null;
  nextPanelIndex: number;
  stepState: PanelGuidedStepState;
};

/**
 * Apply the Python panel-guided transition priorities to one already-scored step.
 */
export function buildPanelGuidedStep(params: BuildPanelGuidedStepParams): BuildPanelGuidedStepResult {
  const { currentFixation, currentPanelIndex, orderedPanels, localRoi, localCandidates, fallbackCandidates, stepIndex } = params;
  const currentPanel = orderedPanels[currentPanelIndex];
  const nextPanel = orderedPanels[currentPanelIndex + 1] ?? null;
  const currentPanelCandidates = filterCandidatesToPanel(localCandidates, currentPanel);
  const nextPanelCandidates = filterCandidatesToPanel(localCandidates, nextPanel);

  let nextFixation: Point | null = null;
  let nextPanelIndex = currentPanelIndex;
  let selectedCandidate: Candidate | null = null;
  let selectedPanelId = currentPanel.panelId;
  let selectedSource: PanelGuidedSelectionSource = "none";
  let note = "Reached the last panel and found no remaining candidate.";

  // Priority 1: remain inside the current panel whenever it still exposes a valid candidate.
  if (currentPanelCandidates.length > 0) {
    selectedCandidate = currentPanelCandidates[0];
    nextFixation = candidateToPoint(selectedCandidate);
    selectedSource = "current_panel";
    note = "Selected the best candidate inside the current panel.";
  }
  // Priority 2: move into the next panel from the original local ROI when possible.
  else if (nextPanel && nextPanelCandidates.length > 0) {
    selectedCandidate = nextPanelCandidates[0];
    nextFixation = candidateToPoint(selectedCandidate);
    selectedPanelId = nextPanel.panelId;
    selectedSource = "next_panel_local";
    nextPanelIndex += 1;
    note = "Current panel had no candidate, so the best next-panel candidate was selected from the local ROI.";
  }
  // Priority 3: after a full-page fallback, use the best next-panel candidate if one exists.
  else if (nextPanel && fallbackCandidates.length > 0) {
    selectedCandidate = fallbackCandidates[0];
    nextFixation = candidateToPoint(selectedCandidate);
    selectedPanelId = nextPanel.panelId;
    selectedSource = "next_panel_full_page";
    nextPanelIndex += 1;
    note = "Selected the best next-panel candidate after expanding the ROI to the full page.";
  }
  // Priority 4: if the next panel still has no candidate, jump to its center.
  else if (nextPanel) {
    nextFixation = panelCenter(nextPanel);
    selectedPanelId = nextPanel.panelId;
    selectedSource = "next_panel_center";
    nextPanelIndex += 1;
    note = "No next-panel candidate existed even after full-page fallback, so the next panel center was used.";
  }

  return {
    nextFixation,
    nextPanelIndex,
    stepState: {
      stepIndex,
      phase: stepIndex === 0 ? "start" : "transition",
      fixation: currentFixation,
      currentPanelIndex,
      currentPanelId: currentPanel.panelId,
      nextPanelId: nextPanel?.panelId ?? null,
      localRoi,
      usedFullPageRoi: fallbackCandidates.length > 0,
      localCandidates,
      fallbackCandidates,
      selectedCandidate,
      selectedFixation: nextFixation,
      selectedPanelId,
      selectedSource,
      actualTransitionScore: selectedCandidate?.finalScore ?? 0,
      note,
    },
  };
}

/**
 * Convert one ranked candidate into a simple page-space fixation point.
 */
export function candidateToPoint(candidate: Candidate): Point {
  return {
    x: candidate.pageX,
    y: candidate.pageY,
  };
}

/**
 * Test whether a page-space point lies inside a panel rectangle.
 */
export function rectContainsPoint(rect: PanelBox["rect"], point: Point): boolean {
  return (
    point.x >= rect.x &&
    point.x <= rect.x + rect.width &&
    point.y >= rect.y &&
    point.y <= rect.y + rect.height
  );
}
